name: my_notes_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  go_router: ^16.2.0
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  intl: ^0.20.2
  jiffy: ^6.4.3
  supabase_flutter: ^2.10.0
  flutter_dotenv: ^6.0.0
  uuid: ^4.5.1
  screenshot: ^3.0.0
  http: ^1.5.0
  share_plus: ^12.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mix_generator: ^1.7.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
